### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by ghettosoulja** [ecksun/Contiki-IDS#3]
i have run the codes in contiki but this issue came out, what should i do?please show me correct path to use this apps

make: ***No rule to make target 'ids-common.sky'. stop.
please returned error code 2

what is this mean about

**Comment by ecksun** [comment]
I'm not sure what you are trying to do, but you can start looking at [run_test.sh](https://github.com/ecksun/Contiki-IDS/blob/f28f2754504e69c2a3dc8a7cbdf21da0642f79f1/examples/ipv6/ids/evaluation/run_test.sh)
