### ISSUE TITLE
problem on IDS result and calculate true positive rate

### ISSUE THREAD

**Issue by smhjafari** [ecksun/Contiki-IDS#4]
Hi,
I want to work with this IDS on my research. So I need working with the code of this IDS and I want to analyze IDS detecting results for sinkHole attack.
for this purpose I need to run  IDS on sinkHole attack and find the method for calculating false positive as this paper said.

Can you help me in these requests?

thank

**Comment by ecksun** [comment]
No, I can't provide support for this project
