### ISSUE TITLE
How to run RPL attacks without using csc file simulation?

### ISSUE THREAD

**Issue by malamo** [ecksun/Contiki-IDS#6]
Dear sir,

I find the implemention of attacks a very great work, I want to integrate them in a real networks (real devices), but I am worried about how to simulate those attacks without using csc files? 
My devices integrate already contiki, I have integrate  code attacks in my  OS. 
But I don't know how to run them without csc file. 
I would be grateful if you could help me please? 

Thank you i advance.

**Comment by ecksun** [comment]
> I find the implemention of attacks a very great work, I want to integrate them in a real networks

Well, thank you, but that does sound a bit worrying :P

>  I would be grateful if you could help me please?

I probably cant, but I might be able to point you in the right direction

[Here](https://github.com/ecksun/Contiki-IDS/blob/test-attacks/examples/ipv6/ids/evaluation/simulations/idle-tree-dense-noloss.csc#L28) you can see how cooja compiles the code, that together with the official contiki documentation on how to build and run things should probably get you where you need to go.

If you want to contribute some improvements on docs or similar on how to do this, I would be happy to accept them

**Comment by SalalAmjad** [comment]
**malamo**

From where did you find the code of RPL attacks?  Actually i am in a same problem because i don't know how to run these simulation in cooja without using csc files. I am actually got stuck in my project which based on IOT Security.

Can anyone please help me?

**Comment by uCipher032** [comment]
@malamo  can you please enlighten me, as to how you ran the csc files? I keep running into errors while trying to run them through cooja, any guidance would be appreciated.
